site_name: DDI questionnaire modeling
site_url: https://inseefr.github.io/ddi-questionnaire-modeling
theme:
  name: material
  language: fr
  icon:
    logo: material/book
  palette:
    scheme: default
    primary: pink
    accent: cyan
  features:
    - navigation.footer
    - navigation.indexes
    - content.code.copy
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/InseeFr/ddi-questionnaire-modeling
nav:
  - Structure: "./structure"
  - Statements: "./statements"
  - Question bank:
      - ALL: "./question-bank"
      - Dynamic table: "./question-bank/dynamic-table.md"
      - Misc: "./question-bank/misc.md"
  - Mandatory question: "./mandatory-question"
  - Parameters: "./parameters"
  - Filter: "./filter"
  - Check: "./check"
  - Loop: "./loop"
  - Roundabout: "./roundabout" 
  - Variable: "./variable"
  - Derived variable: "./derived-variable"
  - Update notes: "./update"
markdown_extensions:
  - admonition
  - tables
  - footnotes
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - glightbox
